---
title: "Raport cen wizyt placówki medycznej"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(dplyr)
library(reactable)
library(crosstalk)
library(ggplot2)

# Wczytanie danych z CSV
doctors <- read_csv("data/doctors.csv")
patients <- read_csv("data/patients.csv")
visits <- read_csv("data/visits.csv")

# Zmieniamy nazwy kolumn przed joinem, by uniknąć konfliktów
doctors <- doctors %>%
  rename(doctor_name = name)

patients <- patients %>%
  rename(patient_name = name)

# Połączenie danych
result <- visits %>%
  left_join(patients, by = "patient_id") %>%
  left_join(doctors, by = "doctor_id") %>%
  select(visit_id, patient_name, doctor_name, specialization, visit_price, visit_date,)
```

```{r}
shared_data <- SharedData$new(result)

reactable(
  shared_data,
  defaultColDef = colDef(
    style = function(value, index, name) {
      list(background = "#e6ffe6", color = "#003300")
    }
  ),
  filterable = TRUE,
  searchable = TRUE,
  striped = TRUE,
  bordered = TRUE
)

```
```{r}

# Raport: średnia cena wizyt wg specjalizacji
report_avg_price <- visits %>%
  filter(visit_price > 0) %>%  # <-- odrzucamy zerowe ceny
  left_join(doctors %>% select(doctor_id, specialization), by = "doctor_id") %>%
  group_by(specialization) %>%
  summarise(avg_price = mean(visit_price, na.rm = TRUE)) %>%
  arrange(desc(avg_price))


ggplot(report_avg_price, aes(x = reorder(specialization, avg_price), y = avg_price)) +
  geom_col(fill = "seagreen") +
  geom_text(aes(label = round(avg_price, 2)), 
            hjust = -0.1, color = "black", size = 3.5) +
  coord_flip() +
  labs(
    title = "Średnia cena wizyt wg specjalizacji",
    x = "Specjalizacja",
    y = "Średnia cena (PLN)"
  ) +
  theme_minimal() +
  expand_limits(y = max(report_avg_price$avg_price) * 1.1)  # trochę miejsca dla etykiet

```

```{r}

ggplot(result, aes(x = specialization, y = visit_price)) +
  geom_boxplot(fill = "lightblue") +
  coord_flip() +
  labs(
    title = "Rozkład cen wizyt w każdej specjalizacji",
    x = "Specjalizacja",
    y = "Cena"
  )

```
